FROM python:3.11-slim

# Définir le dossier de travail
WORKDIR /app

# Copier les dépendances
COPY backend/requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY backend/app ./app
COPY frontend ./frontend


# Commande de lancement
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
